// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("nats")
	ScopeName = "github.com/synadia-io/opentelemetry-collector-nats/receiver/natsreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
	LogsStability    = component.StabilityLevelDevelopment
	TracesStability  = component.StabilityLevelDevelopment
)
